apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedroguedes-playlist-generator-model-deployment
  namespace: pedroguedes
  labels:
    app: pedro-playlist-generator-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedro-playlist-generator-model
  template:
    metadata:
      labels:
        app: pedro-playlist-generator-model
    spec:
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: project2-pv2-pedroguedes
      containers:
        - name: pedro-playlist-generator-model
          image:  pedroufmg/playlist-generator-model:latest
          volumeMounts:
            - name: persistent-volume
              mountPath: /app/data
          ports:
          - containerPort: 5008
          env:
            - name: PLAYLISTS_DATASET_PATH
              value: "/app/data/2023_spotify_ds1.csv"
