apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-pedroguedes
  namespace: pedroguedes
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: pedroguedes
  storageClassName: default-storage-class-pedroguedes